FROM aggregator:latest

COPY ./server/common/aggregators/rolling_average_aggregator /common/aggregators/rolling_average_aggregator
COPY ./server/common/aggregators/aggregate_trip_duration /common/aggregators/aggregate_trip_duration
