FROM aggregator:latest

COPY ./server/common/aggregators/count_aggregator /common/aggregators/count_aggregator
COPY ./server/common/aggregators/aggregate_trip_count /common/aggregators/aggregate_trip_count
