FROM server:latest

COPY ./common_utils /common_utils
COPY ./server/common/utils.py /common/utils.py
COPY ./server/main.py /main.py
COPY ./server/common/dag_node.py /common/dag_node.py
COPY ./server/common/dag_node_factory.py /common/dag_node_factory.py
COPY ./server/common/rabbit /common/rabbit
COPY ./server/common/consumers/stations_consumer /common/consumers/stations_consumer
