
version: '3.9'

x-node: &node
  entrypoint: python /main.py
  links:
    - rabbit
  depends_on:
    - rabbit
  volumes:
    - type: bind
      source: ./server/config.ini
      target: /config.ini
  restart: on-failure

services:
  rabbit:
    container_name: rabbit
    build:
      context: ./rabbit
      dockerfile: Dockerfile
    ports:
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check-port-connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  metrics_consumer:
    <<: *node
    image: metrics_consumer:latest
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_NAME=METRICS_CONSUMER
      - FILTER_BY_COUNT_REPLICAS=1
      - FILTER_BY_DISTANCE_REPLICAS=1
      - AGGREGATE_TRIP_DURATION_REPLICAS=1
    depends_on:
      - rabbit 

  aggregate_trip_distance_0:
    <<: *node
    image: aggregate_trip_distance:latest
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_NAME=AGGREGATE_TRIP_DISTANCE
      - HAVERSINE_APPLIER_REPLICAS=1
      - FILTER_BY_DISTANCE_REPLICAS=1
      - ID=0
    depends_on:
      - filter_by_distance_0

  aggregate_trip_duration_0:
    <<: *node
    image: aggregate_trip_duration:latest
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_NAME=AGGREGATE_TRIP_DURATION
      - JOINER_BY_DATE_REPLICAS=1
      - ID=0
    depends_on:
      - metrics_consumer

  aggregate_trip_count_0:
    <<: *node
    image: aggregate_trip_count:latest
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_NAME=AGGREGATE_TRIP_COUNT
      - JOINER_BY_YEAR_CITY_STATION_ID_REPLICAS=1
      - FILTER_BY_COUNT_REPLICAS=1
      - ID=0
    depends_on:
      - filter_by_count_0

  haversine_applier_0:
    <<: *node
    image: haversine_applier:latest
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_NAME=HAVERSINE_APPLIER
      - HAVERSINE_APPLIER_REPLICAS=1
      - JOINER_BY_YEAR_END_STATION_ID_REPLICAS=1
      - AGGREGATE_TRIP_DISTANCE_REPLICAS=1
      - ID=0
    depends_on:
      - aggregate_trip_distance_0

  joiner_by_year_city_station_id_0:
    <<: *node
    image: joiner_by_year_city_station_id:latest
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_NAME=JOINER_BY_YEAR_CITY_STATION_ID
      - STATIONS_CONSUMER_REPLICAS=1
      - FILTER_BY_YEAR_REPLICAS=1
      - AGGREGATE_TRIP_COUNT_REPLICAS=1
      - ID=0
    depends_on:
      - aggregate_trip_count_0

  joiner_by_date_0:
    <<: *node
    image: joiner_by_date:latest
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_NAME=JOINER_BY_DATE
      - FILTER_BY_PRECIPITATION_REPLICAS=1
      - TRIPS_CONSUMER_REPLICAS=1
      - AGGREGATE_TRIP_DURATION_REPLICAS=1
      - ID=0
    depends_on:
      - aggregate_trip_duration_0

  joiner_by_year_end_station_id_0:
    <<: *node
    image: joiner_by_year_end_station_id:latest
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_NAME=JOINER_BY_YEAR_END_STATION_ID
      - FILTER_BY_CITY_REPLICAS=1
      - HAVERSINE_APPLIER_REPLICAS=1
      - ID=0
    depends_on:
      - haversine_applier_0

  filter_by_count_0:
    <<: *node
    image: filter_by_count:latest
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_NAME=FILTER_BY_COUNT
      - AGGREGATE_TRIP_COUNT_REPLICAS=1
      - ID=0
    depends_on:
      - metrics_consumer

  filter_by_distance_0:
    <<: *node
    image: filter_by_distance:latest
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_NAME=FILTER_BY_DISTANCE
      - AGGREGATE_TRIP_DISTANCE_REPLICAS=1
      - ID=0
    depends_on:
      - rabbit

  filter_by_city_0:
    <<: *node
    image: filter_by_city:latest
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_NAME=FILTER_BY_CITY
      - TRIPS_CONSUMER_REPLICAS=1
      - JOINER_BY_YEAR_END_STATION_ID_REPLICAS=1
      - STATIONS_CONSUMER_REPLICAS=1
      - ID=0
    depends_on:
      - joiner_by_year_end_station_id_0

  filter_by_precipitation_0:
    <<: *node
    image: filter_by_precipitation:latest
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_NAME=FILTER_BY_PRECIPITATION
      - WEATHER_CONSUMER_REPLICAS=1
      - ID=0
    depends_on:  
      - joiner_by_date_0

  filter_by_year_0:
    <<: *node
    image: filter_by_year:latest
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_NAME=FILTER_BY_YEAR
      - TRIPS_CONSUMER_REPLICAS=1
      - JOINER_BY_YEAR_CITY_STATION_ID_REPLICAS=1
      - ID=0
    depends_on:
      - joiner_by_year_city_station_id_0

  weather_consumer_0:
    <<: *node
    image: weather_consumer:latest
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_NAME=WEATHER_CONSUMER
      - FILTER_BY_PRECIPITATION_REPLICAS=1
      - ID=0
    depends_on:
      - filter_by_precipitation_0

  stations_consumer_0:
    <<: *node
    image: stations_consumer:latest
    environment:
      - PYTHONUNBUFFERED=1
      - NODE_NAME=STATIONS_CONSUMER
      - FILTER_BY_CITY_REPLICAS=1
      - ID=0
    depends_on:
      - filter_by_city_0
      - joiner_by_year_city_station_id_0

  trips_consumer_0:
    <<: *node
    image: trips_consumer:latest
    entrypoint: python /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - NODE_NAME=TRIPS_CONSUMER
      - FILTER_BY_CITY_REPLICAS=1
      - FILTER_BY_YEAR_REPLICAS=1
      - JOINER_BY_DATE_REPLICAS=1
      - ID=0
    depends_on:
      - filter_by_city_0
      - filter_by_year_0
      - joiner_by_date_0

  loader:
    <<: *node
    container_name: loader
    image: loader:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - NODE_NAME=LOADER
      - STATIONS_CONSUMER_REPLICAS=1
      - WEATHER_CONSUMER_REPLICAS=1
      - TRIPS_CONSUMER_REPLICAS=1
      - JOINER_BY_DATE_REPLICAS=1
      - JOINER_BY_YEAR_CITY_STATION_ID_REPLICAS=1
      - JOINER_BY_YEAR_END_STATION_ID_REPLICAS=1
      - MAX_CLIENTS=1
      - PORT=8888
    ports:
      - "8888:8888"
    depends_on:
      - trips_consumer_0
      - stations_consumer_0
      - weather_consumer_0
