FROM aggregator:latest

COPY ./server/common/aggregators/rolling_average_aggregator /common/aggregators/rolling_average_aggregator
COPY ./server/common/aggregators/aggregate_trip_distance /common/aggregators/aggregate_trip_distance
